import {
  CARD_SCHEMA_VERSION,
  type InstantRecallCard,
  type RecallVisualMedia,
} from "./schema";

const seedDate = "2026-06-28T00:00:00.000Z";
const sourceNote = "Draft educational seed content. Verify with medical education review before production use.";

type SeedCard = Omit<
  InstantRecallCard,
  | "schemaVersion"
  | "citations"
  | "author"
  | "reviewer"
  | "reviewedAt"
  | "contentVersion"
  | "provenance"
  | "visualMedia"
  | "createdAt"
  | "updatedAt"
> & {
  visualMedia?: RecallVisualMedia[];
};

function seedCard(card: SeedCard): InstantRecallCard {
  return {
    schemaVersion: CARD_SCHEMA_VERSION,
    citations: [
      {
        label: "StepSpark draft seed deck",
        note: "Placeholder citation pending source-level medical review.",
      },
    ],
    author: "StepSpark Seed Deck",
    reviewer: "",
    visualMedia: [],
    contentVersion: 1,
    provenance: "seed",
    createdAt: seedDate,
    updatedAt: seedDate,
    ...card,
  };
}

export const seedInstantRecallCards: InstantRecallCard[] = [
  seedCard({
    id: "irc-001",
    title: "Reed-Sternberg Recognition",
    frontPrompt: "Painless cervical lymphadenopathy with large owl-eye cells on biopsy.",
    visualCue: "Binucleated owl-eye cell in a lymph node field.",
    answer: "Hodgkin lymphoma with Reed-Sternberg cells, classically CD15+ and CD30+.",
    explanation: "The visual trigger is the large bilobed cell with prominent nucleoli in an appropriate lymph node presentation.",
    trap: "Do not confuse with diffuse large B-cell lymphoma, which lacks classic Reed-Sternberg morphology.",
    system: "Hematology",
    discipline: "Pathology",
    difficulty: "medium",
    status: "draft",
    tags: ["lymphoma", "histology", "oncology"],
    sourceNote,
    learningObjective: "Recognize Hodgkin lymphoma from classic Reed-Sternberg morphology and lymphadenopathy clues.",
    highYieldRationale: "This is a common Step 1 pathology image association where cell morphology quickly narrows the answer.",
    visualMedia: [
      {
        id: "media-reed-sternberg-histology",
        kind: "histology",
        title: "Reed-Sternberg cell histology",
        description: "Large binucleated owl-eye cell morphology used as the core recognition anchor for Hodgkin lymphoma.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Reed-sternberg_cell.jpg",
        sourceName: "National Cancer Institute via Wikimedia Commons",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Reed-sternberg_cell.jpg",
        license: "Public domain",
        attribution: "National Cancer Institute",
        provenance: "public-domain",
        useCase: "Use when the answer depends on recognizing classic pathology morphology.",
      },
    ],
  }),
  seedCard({
    id: "irc-002",
    title: "G6PD Oxidative Stress",
    frontPrompt: "Hemolysis after fava beans, sulfa drugs, or infection with bite cells on smear.",
    visualCue: "Red cells with membrane bites and Heinz body clue.",
    answer: "G6PD deficiency causing oxidative hemolysis.",
    explanation: "Low NADPH impairs glutathione recycling, so oxidant stress damages red blood cells.",
    trap: "The trigger is episodic oxidant exposure; chronic baseline hemolysis suggests another process.",
    system: "Hematology",
    discipline: "Biochemistry",
    difficulty: "easy",
    status: "draft",
    tags: ["hemolysis", "enzymes", "red-blood-cells"],
    sourceNote,
    learningObjective: "Identify oxidative hemolysis patterns associated with G6PD deficiency.",
    highYieldRationale: "The exposure history plus bite cells is a rapid-recognition pairing for enzyme deficiency questions.",
    visualMedia: [
      {
        id: "media-g6pd-bite-cells",
        kind: "histology",
        title: "Bite cells on peripheral smear",
        description: "Peripheral smear showing bite-cell morphology after splenic removal of Heinz body inclusions.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/BITE_CELLS.jpg",
        sourceName: "RJDS MEDIX via Wikimedia Commons",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:BITE_CELLS.jpg",
        license: "CC BY-SA 4.0",
        attribution: "RJDS MEDIX (Ronak Darji)",
        provenance: "open-license",
        useCase: "Use when morphology, exposure history, and enzyme deficiency must be linked quickly.",
      },
    ],
  }),
  seedCard({
    id: "irc-003",
    title: "DiGeorge Pattern",
    frontPrompt: "Recurrent viral/fungal infections, hypocalcemia, abnormal facies, and absent thymic shadow.",
    visualCue: "Absent thymus plus low calcium tetany clue.",
    answer: "DiGeorge syndrome from 22q11 deletion with failed third and fourth pharyngeal pouch development.",
    explanation: "Thymic aplasia causes T-cell deficiency; parathyroid aplasia causes hypocalcemia.",
    trap: "Do not label as isolated hypoparathyroidism when immune findings and thymic absence are present.",
    system: "Immunology",
    discipline: "Embryology",
    difficulty: "medium",
    status: "draft",
    tags: ["immunodeficiency", "embryology", "chromosome-22"],
    sourceNote,
    learningObjective: "Connect thymic/parathyroid aplasia with DiGeorge syndrome and 22q11 deletion.",
    highYieldRationale: "Combining immune deficiency with hypocalcemia is a classic integrated embryology clue.",
    visualMedia: [
      {
        id: "media-digeorge-pouches",
        kind: "diagram",
        title: "Third and fourth pouch failure",
        description: "Local vector diagram connecting failed pharyngeal pouch development to thymic and parathyroid aplasia.",
        imageUrl: "/media/instant-recall/digeorge-3-4-pouches.svg",
        sourceName: "StepSpark original vector diagram",
        license: "StepSpark educational draft asset",
        provenance: "stepspark-generated",
        useCase: "Use when the learning target is an embryology mechanism rather than a clinical photograph.",
      },
    ],
  }),
  seedCard({
    id: "irc-004",
    title: "HOCM Maneuver",
    frontPrompt: "Systolic murmur that increases with Valsalva or standing.",
    visualCue: "Narrower left ventricular chamber worsening outflow obstruction.",
    answer: "Hypertrophic obstructive cardiomyopathy.",
    explanation: "Reduced preload makes the ventricular cavity smaller, increasing dynamic outflow obstruction.",
    trap: "Most murmurs get softer with Valsalva; HOCM and MVP are common exceptions.",
    system: "Cardiovascular",
    discipline: "Physiology",
    difficulty: "medium",
    status: "draft",
    tags: ["murmurs", "maneuvers", "cardiology"],
    sourceNote,
    learningObjective: "Predict how preload-reducing maneuvers affect hypertrophic obstructive cardiomyopathy murmurs.",
    highYieldRationale: "Maneuver effects are frequently tested because they distinguish dynamic obstruction from common murmurs.",
    visualMedia: [
      {
        id: "media-hocm-preload",
        kind: "diagram",
        title: "Reduced preload narrows LV cavity",
        description: "Local vector diagram showing why Valsalva or standing worsens dynamic outflow obstruction.",
        imageUrl: "/media/instant-recall/hocm-preload.svg",
        sourceName: "StepSpark original vector diagram",
        license: "StepSpark educational draft asset",
        provenance: "stepspark-generated",
        useCase: "Use when a physiology graph or mechanism diagram is clearer than a static anatomy image.",
      },
    ],
  }),
  seedCard({
    id: "irc-005",
    title: "B12 Neuro Clue",
    frontPrompt: "Macrocytic anemia with paresthesias, impaired vibration sense, and elevated methylmalonic acid.",
    visualCue: "Large oval red cells plus posterior column symptoms.",
    answer: "Vitamin B12 deficiency.",
    explanation: "B12 deficiency impairs DNA synthesis and myelin maintenance, producing anemia plus neurologic findings.",
    trap: "Folate deficiency can cause macrocytosis but should not cause the same neurologic deficits.",
    system: "Hematology",
    discipline: "Nutrition",
    difficulty: "easy",
    status: "draft",
    tags: ["macrocytosis", "vitamins", "neurology"],
    sourceNote,
    learningObjective: "Distinguish vitamin B12 deficiency from folate deficiency using neurologic and lab clues.",
    highYieldRationale: "Neurologic deficits and methylmalonic acid elevate the diagnostic specificity of macrocytosis questions.",
    visualMedia: [
      {
        id: "media-b12-mma-neuro",
        kind: "biochemistry",
        title: "B12 methylmalonic acid neuro separator",
        description: "Local vector pathway highlighting macrocytosis, elevated methylmalonic acid, and posterior column symptoms.",
        imageUrl: "/media/instant-recall/b12-mma-neuro.svg",
        sourceName: "StepSpark original vector diagram",
        license: "StepSpark educational draft asset",
        provenance: "stepspark-generated",
        useCase: "Use when a compact biochemical pathway improves rapid discrimination.",
      },
    ],
  }),
  seedCard({
    id: "irc-006",
    title: "Trousseau Signal",
    frontPrompt: "Migratory thrombophlebitis in a patient with weight loss and epigastric pain radiating to the back.",
    visualCue: "Moving superficial clots plus pancreatic silhouette.",
    answer: "Trousseau syndrome associated with pancreatic adenocarcinoma.",
    explanation: "Mucin-producing adenocarcinomas can create a hypercoagulable state with migratory thromboses.",
    trap: "Do not treat the migrating clot pattern as isolated uncomplicated thrombophlebitis.",
    system: "Gastrointestinal",
    discipline: "Pathology",
    difficulty: "hard",
    status: "draft",
    tags: ["pancreas", "hypercoagulability", "oncology"],
    sourceNote,
    learningObjective: "Associate migratory thrombophlebitis with malignancy-associated hypercoagulability.",
    highYieldRationale: "The moving clot pattern is a compact clue for pancreatic adenocarcinoma and mucin-driven coagulation.",
    visualMedia: [
      {
        id: "media-trousseau-migratory-clots",
        kind: "mnemonic",
        title: "Migratory clots plus pancreas",
        description: "Local vector mnemonic linking migratory thrombophlebitis to mucin-driven malignancy hypercoagulability.",
        imageUrl: "/media/instant-recall/trousseau-migratory-clots.svg",
        sourceName: "StepSpark original vector diagram",
        license: "StepSpark educational draft asset",
        provenance: "stepspark-generated",
        useCase: "Use when a visual mnemonic is more useful than a nonspecific clinical photo.",
      },
    ],
  }),
  seedCard({
    id: "irc-007",
    title: "Duodenal Atresia Image",
    frontPrompt: "Newborn with bilious vomiting and a double-bubble sign on imaging.",
    visualCue: "Two adjacent gas bubbles in the upper abdomen.",
    answer: "Duodenal atresia, classically associated with Down syndrome.",
    explanation: "Failure of duodenal recanalization creates proximal obstruction with the double-bubble pattern.",
    trap: "Bilious vomiting in a newborn is obstruction until proven otherwise; avoid dismissing it as reflux.",
    system: "Gastrointestinal",
    discipline: "Embryology",
    difficulty: "medium",
    status: "draft",
    tags: ["pediatrics", "embryology", "imaging"],
    sourceNote,
    learningObjective: "Recognize duodenal atresia from neonatal bilious vomiting and double-bubble imaging.",
    highYieldRationale: "The double-bubble sign is a high-yield visual diagnosis linked to embryologic recanalization failure.",
    visualMedia: [
      {
        id: "media-duodenal-atresia-double-bubble",
        kind: "radiology",
        title: "Double-bubble radiograph",
        description: "Radiograph showing the classic double-bubble pattern used for duodenal atresia recognition.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Radiograph_with_Double_Bubble_Sign.jpg",
        sourceName: "JasonRobertYoungMD via Wikimedia Commons",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Radiograph_with_Double_Bubble_Sign.jpg",
        license: "CC BY-SA 4.0",
        attribution: "JasonRobertYoungMD",
        provenance: "open-license",
        useCase: "Use when the imaging pattern is the tested recognition anchor.",
      },
    ],
  }),
  seedCard({
    id: "irc-008",
    title: "Papillary Thyroid Cue",
    frontPrompt: "Thyroid cancer with Orphan Annie eye nuclei and psammoma bodies.",
    visualCue: "Clear nuclei with laminated calcified spheres.",
    answer: "Papillary thyroid carcinoma.",
    explanation: "The nuclear clearing and psammoma bodies are classic rapid-recognition pathology cues.",
    trap: "Amyloid stroma points toward medullary thyroid carcinoma, not papillary carcinoma.",
    system: "Endocrine",
    discipline: "Pathology",
    difficulty: "easy",
    status: "draft",
    tags: ["thyroid", "histology", "oncology"],
    sourceNote,
    learningObjective: "Identify papillary thyroid carcinoma by its histologic nuclear and calcification cues.",
    highYieldRationale: "Thyroid cancer questions often hinge on recognizing signature histology and avoiding medullary traps.",
    visualMedia: [
      {
        id: "media-papillary-thyroid-fna",
        kind: "pathology",
        title: "Papillary thyroid carcinoma FNA",
        description: "Open pathology image supporting recognition of papillary thyroid carcinoma cytology and nuclear pattern.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Papillary_Carcinoma_of_Thyroid%2C_FNA_%283153794407%29.jpg",
        sourceName: "Ed Uthman via Wikimedia Commons",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Papillary_Carcinoma_of_Thyroid,_FNA_(3153794407).jpg",
        license: "CC BY 2.0",
        attribution: "Ed Uthman from Houston, TX, USA",
        provenance: "open-license",
        useCase: "Use when histology/cytology pattern recognition is the main recall task.",
      },
    ],
  }),
  seedCard({
    id: "irc-009",
    title: "Sarcoid Granuloma",
    frontPrompt: "Bilateral hilar lymphadenopathy, noncaseating granulomas, and elevated ACE.",
    visualCue: "Tight granuloma without central caseation.",
    answer: "Sarcoidosis.",
    explanation: "Noncaseating granulomas in the lungs with hilar adenopathy are the recognition anchor.",
    trap: "Caseating granulomas should push tuberculosis or fungal infection higher.",
    system: "Respiratory",
    discipline: "Pathology",
    difficulty: "medium",
    status: "draft",
    tags: ["granuloma", "pulmonary", "immunology"],
    sourceNote,
    learningObjective: "Differentiate sarcoidosis from infectious granulomatous disease using granuloma type and chest clues.",
    highYieldRationale: "Noncaseating granulomas plus bilateral hilar lymphadenopathy is a frequent rapid-recognition pattern.",
    visualMedia: [
      {
        id: "media-sarcoidosis-granuloma",
        kind: "histology",
        title: "Sarcoidosis granulomatous histology",
        description: "Open histology image used to reinforce granulomatous tissue pattern recognition in sarcoidosis.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Sarcoidosis_histology_skin_involvement.jpg",
        sourceName: "Jensflorian via Wikimedia Commons",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Sarcoidosis_histology_skin_involvement.jpg",
        license: "CC BY-SA 4.0",
        attribution: "Jensflorian",
        provenance: "open-license",
        useCase: "Use when tissue pattern, not just the text clue, should drive rapid recognition.",
      },
    ],
  }),
  seedCard({
    id: "irc-010",
    title: "Behcet Triad",
    frontPrompt: "Recurrent painful oral ulcers, genital ulcers, and uveitis.",
    visualCue: "Mucosal ulcers plus inflamed eye.",
    answer: "Behcet disease, a variable-vessel vasculitis associated with HLA-B51.",
    explanation: "The recurring oral-genital ulcer pattern with eye inflammation is the rapid clue.",
    trap: "Single-site aphthous ulcers alone are not enough; the multisystem recurrence pattern matters.",
    system: "Immunology",
    discipline: "Pathology",
    difficulty: "hard",
    status: "draft",
    tags: ["vasculitis", "ulcers", "uveitis"],
    sourceNote,
    learningObjective: "Recognize Behcet disease from recurrent oral/genital ulcers and uveitis.",
    highYieldRationale: "The triad is concise and discriminating for variable-vessel vasculitis questions.",
    visualMedia: [
      {
        id: "media-behcet-triad",
        kind: "mnemonic",
        title: "Oral-genital-ocular triad",
        description: "Local vector mnemonic for the recurrent oral ulcers, genital ulcers, and uveitis pattern.",
        imageUrl: "/media/instant-recall/behcet-triad.svg",
        sourceName: "StepSpark original vector diagram",
        license: "StepSpark educational draft asset",
        provenance: "stepspark-generated",
        useCase: "Use when a clean mnemonic grouping supports rapid recognition better than a clinical photo.",
      },
    ],
  }),
];
